# APRSRunner - Windbeidl über Kötschach-Mauthen
# Balloon circles the town, flies the Karnische ridge, visits OE8XEF-10 often

aprs_is:
  callsign: "N0CALL"       # Override with APRS_CALLSIGN env var
  passcode: "00000"         # Override with APRS_PASSCODE env var
  host: "rotate.aprs2.net"
  port: 14580

object:
  name: "Windbeidl"         # 9 chars, max APRS limit
  symbol_table: "/"
  symbol: "O"               # Balloon!
  comment: "A Windbeidl über da Mautneralm! https://oeradio.at"
  comments:
    - "I schweb über olle Gipfl! https://oeradio.at"
    - "Vo do oben schaut olls kluan aus! https://oeradio.at"
    - "Da Wind tragt mi wohin a will! https://oeradio.at"
    - "A Windbeidl über da Mautneralm! https://oeradio.at"
    - "I bin da höchste Kärntna! https://oeradio.at"
    - "Heisse Luft und scheene Aussicht! https://oeradio.at"
    - "Unta mir de Enzianhittn! https://oeradio.at"
    - "Do oben gibts kan Stau! https://oeradio.at"
    - "I brauch kan Weg, i flieg! https://oeradio.at"
    - "Auffi geht's, owi schaug i! https://oeradio.at"

movement:
  speed_kmh: 10.0           # Gentle balloon drift
  beacon_interval: 120      # Every 2 minutes
  loop: true                # Endless floating

route:
  waypoints:
    # Start at OE8XEF-10, circle clockwise around Kötschach-Mauthen
    - [46.6593, 12.9779]    # OE8XEF-10 (start)
    - [46.6680, 12.9850]    # Mauthen
    - [46.6900, 12.9850]    # Sittmoos (north)
    - [46.6950, 13.0000]    # Laas
    - [46.6850, 13.0100]    # Kötschach Nord
    - [46.6720, 13.0060]    # Kötschach Zentrum
    - [46.6750, 13.0300]    # Würmlach (east)
    # Karnische ridge flight: east to west along the peaks
    - [46.6248, 13.0637]    # Zollnerhöhe (1931m)
    - [46.6286, 13.0167]    # Würmlacher Höhe (1581m)
    - [46.6255, 12.9910]    # Elferspitz (2254m)
    - [46.6276, 12.9821]    # Polinik (2332m)
    # Return to OE8XEF-10
    - [46.6593, 12.9779]    # OE8XEF-10 (2nd visit)
    # Detour up to Mautneralm
    - [46.6547, 12.9755]    # Enzianhütte (1496m)
    - [46.6530, 12.9745]    # Mautneralm Gipfel (1720m)
    - [46.6547, 12.9755]    # Enzianhütte (return)
    - [46.6593, 12.9779]    # OE8XEF-10 (3rd visit, close loop)
